name: dsbmobile
description: Implementation of the DSBmobile mobile API in Dart.
version: 1.0.0
homepage: https://github.com/sebiIO/dsbmobile-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
